Modify post rollout bash command 3

diff --git a/.github/workflows/deploy-container.yml b/.github/workflows/deploy-container.yml
--- a/.github/workflows/deploy-container.yml
+++ b/.github/workflows/deploy-container.yml
@@ -31,17 +31,16 @@ jobs:
       # Optional, only for Laravel:
       post_rollout_cmd: >
         docker compose -f docker-compose.prod.yml exec -T app bash -lc '
-          set -e
+          set -eo pipefail
           ARTISAN=/var/www/artisan
           if [ ! -f "$ARTISAN" ]; then
-            echo "ERROR: $ARTISAN not found. Contents of /var/www:"; ls -la /var/www; exit 1;
+            echo "ERROR: $ARTISAN not found. Listing /var/www:"; ls -la /var/www; exit 1;
           fi
           rm -f /var/www/bootstrap/cache/*.php || true
           php "$ARTISAN" config:clear
           php "$ARTISAN" migrate --force
           php "$ARTISAN" config:cache
           php "$ARTISAN" storage:link || true
-        '
 
     secrets:
       host: ${{ secrets.SSH_HOST }}
